name: develop $(Date:yyyyMMdd)$(Rev:.rr)

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: quality
    displayName: Quality
    dependsOn: [build]
    variables:
      - group: resume
    jobs:
      - job: codacy
        displayName: Codacy
        timeoutInMinutes: 5
        steps:
          - checkout: self
            fetchDepth: 0
            displayName: Checkout repository
          - script: |
              curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
              cd codacy-analysis-cli-* && sudo make install
            displayName: Download and install Codacy
          - script: |
              codacy-analysis-cli analyze --commit-uuid $(Build.SourceVersion) --directory $(System.DefaultWorkingDirectory) --verbose --upload
            displayName: Codacy analysis
            env:
              CODACY_PROJECT_TOKEN: $(CODACY_PROJECT_TOKEN)
          - script: |
              bash <(curl -Ls https://coverage.codacy.com/get.sh) report --commit-uuid $(Build.SourceVersion) --coverage-reports $(Pipeline.Workspace)/coverage/lcov.info --partial
              bash <(curl -Ls https://coverage.codacy.com/get.sh) report --commit-uuid $(Build.SourceVersion) --coverage-reports $(Pipeline.Workspace)/coverage/cobertura-coverage.xml --partial
              bash <(curl -Ls https://coverage.codacy.com/get.sh) final --commit-uuid $(Build.SourceVersion)
            displayName: Codacy coverage
            env:
              CODACY_PROJECT_TOKEN: $(CODACY_PROJECT_TOKEN)