name: try $(Date:yyyyMMdd)$(Rev:.rr)

trigger: none
#  tags:
#    include:
#    - azuredevops_*
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: resume

stages:
  - stage: build
    displayName: Build
    dependsOn: []
    jobs:
      - job: prod
        displayName: Prod
        timeoutInMinutes: 5
        steps:
          - checkout: self
            fetchDepth: 0
            displayName: checkout repository
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: setup node and npm
          - script: |
              npm install
              npm run build:prod
            displayName: build with npm for prod
          - script: npm run test
            displayName: run unit tests
          - script: sed -i "s/\/home\/runner\/work\/resume\/resume\///g" coverage/tests-report.xml
            displayName: change path in test report
          - script: |
              npx eslint "src/**/*.{js,vue}" --format stylish
              npx eslint "src/**/*.{js,vue}" --format json --output-file coverage/eslint.json
            displayName: eslint scan
          - script: |
              grep '"version":' package.json | grep '"version":' package.json | sed 's/.*\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\).*/\1/g' > VERSION.md
            displayName: create VERSION.md
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: dist
            displayName: publish dist
          - publish: $(System.DefaultWorkingDirectory)/coverage
            artifact: coverage
            displayName: publish coverage
          - publish: $(System.DefaultWorkingDirectory)/package.json
            artifact: package
            displayName: publish package
          - publish: $(System.DefaultWorkingDirectory)/VERSION.md
            artifact: version
            displayName: publish version
  - stage: publish
    displayName: Publish
    dependsOn: [build]
    jobs:
      - job: release
        displayName: Release
        timeoutInMinutes: 5
        variables:
          - name: version
            value: null
        steps:
          - checkout: none
          - download: current
            artifact: version
            displayName: download version artifact
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: setup node and npm
          - script: |
              VERSION=$(cat "$(Pipeline.Workspace)/version/VERSION.md")
              echo "##vso[task.setvariable variable=version]$VERSION"
            displayName: add version variable
          - script: |
              npm config set registry https://pkgs.dev.azure.com/tdesaules/resume/_packaging/packages/npm/registry/
              npm install @tdesaules/resume@$(version) --prefix $(System.DefaultWorkingDirectory)
            displayName: download @tdesaules/resume package
          - script: |
              tar -cvzf $(System.DefaultWorkingDirectory)/dist.tar.gz $(System.DefaultWorkingDirectory)/node_modules/@tdesaules/resume/dist/*
            displayName: create dist archive
          - task: GitHubRelease@0
            inputs:
              gitHubConnection: github.com_tdesaules
              repositoryName: tdesaules/resume
              action: create
              tagSource: manual
              tag: $(version)
              title: AzureDevops/$(version)
              assets: $(System.DefaultWorkingDirectory)/dist.tar.gz
            displayName: create github release