name: try $(Date:yyyyMMdd)$(Rev:.rr)

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: resume

stages:
  - stage: download
    displayName: Download
    dependsOn: []
    jobs:
      - job: release
        displayName: Release
        timeoutInMinutes: 5
        steps:
          - checkout: none
          - task: DownloadGitHubRelease@0
            inputs:
              connection: github.com_tdesaules
              userRepository: tdesaules/resume
              downloadPath: $(System.DefaultWorkingDirectory)
            displayName: download lasted release