FROM alpine:3.12

RUN apk update
RUN apk add --no-cache wget coreutils ca-certificates git openssh-client bash libgcc libstdc++ curl unzip procps krb5-libs libintl libssl1.1 lttng-ust tzdata userspace-rcu zlib shadow
RUN apk add --no-cache nodejs npm